### ISSUE TITLE
Simplify browsefile.json included in /releases 

### ISSUE THREAD

**Issue by n2j3** [browsefile/backend#3]
**Description**
A clear and concise description of what the issue is about. What are you trying to do?
**Attemping to run ./bf after a clean "installation"**

**Expected behaviour**
What did you expect to happen?
Either break for not having a correct configuration or run with a minimal/default config.

**What is happening instead?**
`using config at path : browsefile.json
2019/10/08 11:20:12 config : Cant create share path for user  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create files path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user1/files /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user1/wd/files: no such file or directory
2019/10/08 11:20:12 config : Cant create shares path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user1/shares /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user1/wd/shares: no such file or directory
2019/10/08 11:20:12 config : Cant create share path for user  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create files path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user2/files /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user2/wd/files: no such file or directory
2019/10/08 11:20:12 config : Cant create shares path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user2/shares /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user2/wd/shares: no such file or directory
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for user  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create files path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user3/files /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user3/wd/files: no such file or directory
2019/10/08 11:20:12 config : Cant create shares path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user3/shares /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/user3/wd/shares: no such file or directory
2019/10/08 11:20:12 config : Cant create share path for user  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create files path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/admin/files /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/admin/wd/files: no such file or directory
2019/10/08 11:20:12 config : Cant create shares path, at dav  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create user files path, at dav  symlink /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/admin/shares /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp2/admin/wd/shares: no such file or directory
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 config : Cant create share path for userF  mkdir /run/media: permission denied
2019/10/08 11:20:12 Listening http://127.0.0.1:8081
2019/10/08 11:20:12 dav://127.0.0.1:8081/wd
2019/10/08 11:20:12 
2019/10/08 11:20:12 Listening https://127.0.0.1:8082
2019/10/08 11:20:12 davs://127.0.0.1:8082/wd
2019/10/08 11:20:12 open /run/media/v/1390ab77-3888-441a-ac20-cb46d9511e27/tmp/server.crt: no such file or directory

**Comment by vitaliy-kuzmich** [comment]
@n2j3  The issue you are experience, are about the user you run the bf, does not have permission to modify directory. Overall yes, currently it is not possible to run it without config file, will fix.

**Comment by vitaliy-kuzmich** [comment]
ready, check 0.8.4
